MGMT-12326: Can't see NHC pause reason in the pop-up window on the status
medik8s/node-remediation-console pull request #15
Opened 2022-11-24 13:14 UTC by batzionb

2022-11-24 13:39 UTC, batzionb commented
Improved pause status popover to show the pause reasons
![image](https://user-images.githubusercontent.com/22211154/203797467-b0897a01-21ad-46ed-b74d-b635289677e0.png)
![image](https://user-images.githubusercontent.com/22211154/203797660-624d0f0e-1da0-46ba-a1cf-026b326fb5fe.png)
![image](https://user-images.githubusercontent.com/22211154/203797729-438f9b43-555a-4750-83d6-c313fba3a03f.png)
![image](https://user-images.githubusercontent.com/22211154/203797906-89a7b7d3-bdc6-47de-b08f-2c1c0a1ea281.png)

2022-11-24 13:44 UTC, batzionb commented
Includes small improvements:
1. Fixed the "Unpause node health check" dialog to show the reasons in bullets same as in popover
2. Fixed all Alerts to be inline
3. Added missing aria labels to TextInput fields to prevent console errors
4. Grammer fixing of node health check conflic with machine health check message

2022-11-28 08:07 UTC, rawagner requested changes

2022-11-28 08:07 UTC, rawagner commented on src/components/details/NodeHealthCheckStatus.tsx
> +            <EllipsisToolTip content={reason}>
missing `key`

2022-11-28 08:07 UTC, rawagner commented on src/components/details/NodeHealthCheckStatus.tsx
> +              <TextListItem className="nhc--enhanced-text-list__list-item">
```suggestion
              <TextListItem className="nhc-enhanced-text-list__list-item">
```

2022-11-28 10:17 UTC, rawagner approved these changes

2022-11-28 10:19 UTC, merged